const LITERAL_CONSTANTS = {
  STYLE_CHANGE_TARGET_BREAKPOINT: 'md',
  SHOP_CARD_MEDIA_VISIBLE_CHANGE_TARGET_BREAKPOINT: 'sm',
  SHOP_CARD_MEDIA_COLLAPSED_SIZE: 150,
} as const;

export const CONSTANTS = {
  ...LITERAL_CONSTANTS,
};
