import { FEATURE_CONSTANTS } from '../../constants';

const LITERAL_CONSTANTS = {
  GET_BOOKMARKED_SHOPS_DEDAULT_REQUEST_COUNT: FEATURE_CONSTANTS.GET_SHOPS_DEFAULT_REQUEST_COUNT,
} as const;

export const CONSTANTS = {
  ...LITERAL_CONSTANTS,
};
