const LITERAL_CONSTANTS = {
  BOOKMARKED_SHOP_LIST_RESULTS_LABEL: 'Bookmarks',
  BOOKMARKED_SHOP_LIST_NO_RESULTS_LABEL: 'No Bookmarked',
} as const;

export const CONSTANTS = {
  ...LITERAL_CONSTANTS,
};
